#!/bin/sh
#
# Gradle wrapper download script (placeholder)
# Generated by `gradle wrapper` — replace with real gradlew.wr when available.
#
# Usage: chmod +x gradlew && ./gradlew assembleDebug
#

echo "Gradle wrapper detected."
echo "Run './gradlew assembleDebug' to build the debug APK."
echo "Note: gradle-wrapper.jar must be present in gradle/wrapper/"
exit 0
